package pl.exercise.spring.mvc.entity;

public enum BookCategoryType {
	ARTS, PHOTOGRAPHY, BIOGRAPHIES, MEMOIRS, BUSINESS, MONEY, CHILDRENS_EBOOKS, COMICS, GRAPHIC_NOVELS, COMPUTERS, TECHNOLOGY, COOKBOOKS, FOOD, WINE, CRAFTS, HOBBIES, HOME, EDUCATION, TEACHING, ENGINEERING, TRANSPORTATION, FOREIGN_LANGUAGES, HEALTH, FITNESS, DIETING, HISTORY, HUMOR, ENTERTAINMENT, LAW, LITERATURE, FICTION, MEDICAL_EBOOKS, MYSTERY, THRILLER, SUSPENSE, NONFICTION, PARENTING, RELATIONSHIPS, POLITICS, SOCIAL_SCIENCES, REFERENCE, RELIGION, SPIRITUALITY, ROMANCE, SCIENCE, MATH, SCIENCE_FICTION, FANTASY, SELFHELP, SPORTS, OUTDOORS, TEEN, YOUNG_ADULT, TRAVEL
}
